package com.cauesobral.vitalis.model;

// Especialidades dos médicos
public enum Specialty {
    CARDIOLOGY,
    DERMATOLOGY,
    ENDOCRINOLOGY,
    GASTROENTEROLOGY,
    HEMATOLOGY,
    NEPHROLOGY,
    NEUROLOGY,
    ONCOLOGY,
    OPHTHALMOLOGY,
    ORTHOPEDICS,
    OTORHINOLARYNGOLOGY,
    PULMONOLOGY,
    RHEUMATOLOGY,
    UROLOGY,
    PEDIATRICS,
    OBSTETRICS_AND_GYNECOLOGY,
    FAMILY_MEDICINE,
    GENERAL_PRACTICE,
    EMERGENCY_MEDICINE,
    ANESTHESIOLOGY,
    RADIOLOGY,
    PATHOLOGY,
    PSYCHIATRY
}
